import type { Metadata } from "next";
import "./globals.css";
import { Anton } from "next/font/google";
import Nav from "@/components/Nav";
import PageTransition from "@/components/PageTransition";

//
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const anton = Anton({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-anton",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className={anton.variable}>
      <body>
        <PageTransition>
          <main className="relative min-h-svh w-full bg-container-bg">
            <Nav />
            {children}
          </main>
        </PageTransition>
      </body>
    </html>
  );
}
